# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e3c6df0e7669a438f16b27083aa321d0"
application_url = "https://carouselslider-sandy.vercel.app/"
embedded = true
name = "Carousel Slider"
handle = "slide-extension"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/privacy"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/update"
  topics = [ "shop/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/subscription"
  topics = [ "app_subscriptions/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://carouselslider-sandy.vercel.app/auth/callback",
  "https://carouselslider-sandy.vercel.app/auth/shopify/callback",
  "https://carouselslider-sandy.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://carouselslider-sandy.vercel.app/proxy"
subpath = "carousel"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true

[pos]
embedded = false
